all:
  vars:
    virl_lab: Dual
    virl_lab_file: "../../../testbeds/dual/files/cml.yaml"
    virl_path: "../../../testbeds/dual/"
    vcenter_host: "{{ lookup('env','VCENTER_HOST') }}"
    vcenter_username: "{{ lookup('env','VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env','VCENTER_PASSWORD') }}"
    virl_host: "{{ lookup('env','VIRL_HOST') }}"
    virl_username: "{{ lookup('env','VIRL_USERNAME') }}"
    virl_password: "{{ lookup('env','VIRL_PASSWORD') }}"
    jumpserver_username: "{{ lookup('env', 'JUMPSERVER_USERNAME') }}"
    jumpserver_password: "{{ lookup('env', 'JUMPSERVER_PASSWORD') }}"
    jumpserver_host: "{{ lookup('env', 'JUMPSERVER_HOST') }}"
    jumpserver_cfg_path: "{{ lookup('env', 'JUMPSERVER_CFG_PATH') }}"
  children:
    controllers:
      hosts:
        vdnac:
        vise:
    nodes:
      vars:
        ansible_network_os: ios
        ansible_connection: network_cli
        ansible_user: "{{ lookup('env','NODE_USERNAME') | default('admin', true) }}"
        ansible_password: "{{ lookup('env','NODE_PASSWORD') | default('cisco', true) }}"
        ansible_become: true
        ansible_become_password: "{{ lookup('env','NODE_ENABLE') | default('cisco', true) }}"
        domain: lab.net
      children:
        transport:
          hosts:
            fusion-1:
              ansible_host: 10.5.39.44
            shared-services:
            mgmt-bcp-1:
            mgmt-bcp-2:
            mgmt-e-1:
            mgmt-e-2:
        fabric:
          children:
            borders:
              hosts:
                bcp-1:
                  ansible_host: 10.5.39.18
                  management_ip: 10.5.39.18
                  management_mask: 255.255.255.0
                  management_gateway: 10.5.39.1
                bcp-2:
                  ansible_host: 10.5.39.19
                  management_ip: 10.5.39.19
                  management_mask: 255.255.255.0
                  management_gateway: 10.5.39.1
            edges:
              hosts:
                e-1:
                  ansible_host: 10.5.39.20
                  management_ip: 10.5.39.20
                  management_mask: 255.255.255.0
                  management_gateway: 10.5.39.1
                e-2:
                  ansible_host: 10.5.39.21
                  management_ip: 10.5.39.21
                  management_mask: 255.255.255.0
                  management_gateway: 10.5.39.1
    linux:
      children:
        endpoints:
          hosts:
            c-1:
            c-2:
            c-3:
